---
- hosts: all
  become: yes
  tasks:
  - name: install packages
    yum: name={{ item }} state=latest 
    with_items:
      - epel-release
      - openvpn
      - easy-rsa
      - policycoreutils-python