---
- hosts: all
  become: yes
  tasks:
  - name: install packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - epel-release
      - openvpn
      - easy-rsa
      - policycoreutils-python

  - name: Change the openvpn_t server to permissive
    selinux_permissive:
      name: openvpn_t
      permissive: true

  - name: Copy server.conf
    copy:
      src: server.conf
      dest: /etc/openvpn/server/server.conf
      owner: root
      group: root
      mode: '0644'

  - name: Gen cert and keys
    shell: |
      /usr/share/easy-rsa/3/easyrsa --batch init-pki
      /usr/share/easy-rsa/3/easyrsa --batch build-ca nopass
      /usr/share/easy-rsa/3/easyrsa --batch gen-dh
      /usr/share/easy-rsa/3/easyrsa --batch --req-cn={{ ansible_facts['hostname'] }} --req-c=RU --req-st=State --req-city=Moscow --req-org=HOME --req-email=p.shekur@otus.ru --req-ou=OTUS gen-req server nopass
      /usr/share/easy-rsa/3/easyrsa --batch sign-req server server 
      /usr/share/easy-rsa/3/easyrsa --batch --req-cn=client1 --req-c=RU --req-st=State --req-city=Moscow --req-org=HOME --req-email=p.shekur@otus.ru --req-ou=OTUS gen-req client1 nopass
      /usr/share/easy-rsa/3/easyrsa --batch sign-req client client1
      cp /etc/openvpn/pki/ca.crt /vagrant/
      cp /etc/openvpn/pki/issued/client1.crt /vagrant/
      cp /etc/openvpn/pki/private/client1.key /vagrant/
    args:
      chdir: /etc/openvpn/

# name: Copy client cert
#      fetch:
#        src: "{{ item }}"
#        dest: ./clients_certs/
#        flat: yes
#        fail_on_missing: no
#      with_items:
#        - /etc/openvpn/pki/ca.crt
#        - /etc/openvpn/pki/ta.key
#        - /etc/openvpn/pki/issued/client1.crt
#        - /etc/openvpn/pki/private/client1.key
#    when: ansible_hostname == "openvpn-server"

  - name: Start openvpn service
    systemd:
      state: started
      name: openvpn-server@server
      enabled: yes