  
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :"server" => {
    :box_name => "centos/7",
    :ip_addr => "172.20.10.55",
    :memory => "256",
    :shell => "server.sh",
    :ansible => "server.yml"
  },
  :"client" => {
    :box_name => "centos/7",
    :ip_addr => "172.20.10.56",
    :memory => "256",
    :shell => "client.sh",
    :ansible => "client.yml"
  }
}

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider "virtualbox" do |vb|
        vb.name = boxname.to_s
        vb.memory = boxconfig[:memory]
        end
      # box.vm.provision "shell", path: boxconfig[:shell]
      box.vm.provision "ansible_local" do |ansible|
        ansible.playbook = boxconfig[:ansible]
        end
    end
  end
end